org: ulyana
app: shellf-bot
service: shellf-bot
frameworkVersion: "3"

dashboard:
  disableMonitoring: true

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 256
  #  timeout: 15 # in seconds
  region: eu-central-1
  #  tracing:
  #    lambda: true
  httpApi:
    cors: true

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - ssm:GetParameter
          Resource:
            - arn:aws:ssm:eu-central-1:959316667373:parameter/*

functions:
  bot_handler:
    handler: lambdas/bot.handler
    timeout: 10
    events:
      - httpApi: POST /rentBook
    environment:
      TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN_SHELLF}
      CLIENT_EMAIL: ${env:SHELLF_CLIENT_EMAIL}
      PRIVATE_KEY: ${env:SHELLF_PRIVATE_KEY}
      NODE_ENV: 'production'
  backend_handler:
    handler: lambdas/backend.handler
    timeout: 5
    events:
      - httpApi:
          method: GET
          path: /book/{bookID}
    environment:
      NODE_ENV: 'production'
  reminder_handler:
    handler: lambdas/reminder.handler
    timeout: 5
    events:
      - schedule: cron(0 13 * * ? *)
    #      - schedule: rate(2 minutes)
    environment:
      TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN_SHELLF}
      NODE_ENV: 'production'